### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by kleinfe** [bloxberg-org/bloxberg-homepage#10]
![grafik](https://user-images.githubusercontent.com/1484773/57679361-67e14a80-762b-11e9-919a-73c1145de75f.png)

**Comment by crossoveranx** [comment]
I added the relevant SEO tags, keywords, and description. I believe google still has to crawl the website which hasn't happened yet. I will leave open until it updates in the search results

**Comment by crossoveranx** [comment]
Confirmed description, title and keywords SEO has been added
